spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#devtools:
#  restart:
#    log-condition-evaluation-delta: false #禁用报告的日志记录
      
#配置springboot读取属性
devconfig:
  ip: 222.247.57.14win
  port: 1433
